SELECT ID_PARAMETRE,B.CODE_POSTE,RUBR_ETAT_LIBELLE,ANNEE_B_DETAIL,VALEUR_B_DETAIL,RUBR_ETAT_TYPE,RUBR_TYPE_DETAIL_VALEUR,RUBR_ETAT_SENS,RUBR_ETAT_CR,RUBR_TYPE_DETAIL_VALEUR,MODE,RUBR_PERCENT,TYPE_ANAFI_A
		FROM ANAFI_BILAN  B,ANAFI_BILAN_DETAIL DB, ANFI_RUBRIQUE_ETAT R, ANAFI_PARAMETRE_DETAIL P
		WHERE B.CODE_POSTE = R.RUBR_ETAT_CODE 
			AND DB.ID_BILAN= B.ID_BILAN
			AND B.ID_PARAMETRE_DETAIL= P.ID_PARAMETRE_DETAIL
			--AND P.ID_PARAMETRE IN (SELECT [ID_PARAMETRE] FROM [ANAFI_PARAMETRE] where [ID_DOSSIER]=@id_dossier )
			--AND B.CODE_POSTE=@code_poste  
			AND RUBR_ETAT_TYPE='BIN'
			AND TYPE_ANAFI_A='SN'
	--ORDER BY RUBR_PERCENT,DATE_CLOTURE
		ORDER BY RUBR_PERCENT,RIGHT(ANNEE_DETAIL, 4)



		select * from [ANAFI_PARAMETRE] WHERE  ID_PARAMETRE=2204
		select * from SCOR_DOSSIER WHERE  ID_DOSSIER=2204
		select * from SCOR_CONTREPARTIE WHERE  ID_SCORING='SC00002204'
		