use ScoringDB
GO
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'CODE_BANQUE'
          AND Object_ID = Object_ID(N'dbo.SCOR_SEUIL_DELEGUATION'))
BEGIN
	ALTER TABLE SCOR_SEUIL_DELEGUATION ADD CODE_BANQUE T_CODE_5 null
End

go
IF EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'CODE_BANQUE'
          AND Object_ID = Object_ID(N'dbo.SCOR_SEUIL_DELEGUATION'))
BEGIN
	ALTER TABLE SCOR_SEUIL_DELEGUATION ADD CONSTRAINT FK_SEUIL_BANQUE Foreign key (CODE_BANQUE)
		references SCOR_BANQUE(CODE_BANQUE)

update SCOR_SEUIL_DELEGUATION set CODE_BANQUE=(select Top 1 CODE_BANQUE 
			from SCOR_AGENCE A, SCOR_UTILISATEUR U where A.CODE_AGENCE=U.CODE_AGENCE)

End
GO
--IF NOT EXISTS(SELECT 1 FROM sys.columns 
--          WHERE Name = N'CODE_BANQUE'
--          AND Object_ID = Object_ID(N'dbo.SCOR_DELEGATION'))
--BEGIN
--	ALTER TABLE SCOR_DELEGATION ADD CODE_BANQUE T_CODE_5 null

	
--END
--GO

if OBJECT_ID('PS_SCOR_Selection_List_Seuil','P') is not null 
DROP Procedure PS_SCOR_Selection_List_Seuil
GO
Create Procedure PS_SCOR_Selection_List_Seuil
@CODE_BANQUE T_CODE_5 null
As
Begin
	if @CODE_BANQUE is null set @CODE_BANQUE='%'
	Select * from SCOR_SEUIL_DELEGUATION where CODE_BANQUE like @CODE_BANQUE order by MAX_SCOR_SEUIL_DELEGUATION
End

GO
if OBJECT_ID('PS_SCOR_Insert_SchemaDelegataire_A','P') is not null 
Drop Procedure PS_SCOR_Insert_SchemaDelegataire_A
GO
Create Procedure PS_SCOR_Insert_SchemaDelegataire_A
@LIBELLE_SEUIL_DELEGUATION varchar(100)
,@MAX_SCOR_SEUIL_DELEGUATION bigint
,@MIN_SCOR_SEUIL_DELEGUATION bigint
,@CODE_BANQUE varchar(50)
As
Begin
declare @ID_SCOR_SEUIL_DELEGUATION int =0
SELECT @ID_SCOR_SEUIL_DELEGUATION=MAX(ISNULL(ID_SCOR_SEUIL_DELEGUATION,0)) FROM SCOR_SEUIL_DELEGUATION 
SET @ID_SCOR_SEUIL_DELEGUATION=ISNULL(@ID_SCOR_SEUIL_DELEGUATION,0)+1

	if (select count(*) from SCOR_BANQUE where CODE_BANQUE = @CODE_BANQUE)>0
	Begin
		INSERT INTO SCOR_SEUIL_DELEGUATION
			   (ID_SCOR_SEUIL_DELEGUATION, LIBELLE_SEUIL_DELEGUATION
			   , MAX_SCOR_SEUIL_DELEGUATION, MIN_SCOR_SEUIL_DELEGUATION,CODE_BANQUE)
		 VALUES
			   (@ID_SCOR_SEUIL_DELEGUATION, @LIBELLE_SEUIL_DELEGUATION
			   ,@MAX_SCOR_SEUIL_DELEGUATION, @MIN_SCOR_SEUIL_DELEGUATION, @CODE_BANQUE)
	End
End

GO

