USE [ScoringDB]
GO

--RAJOUT  ELOI 14032023
----------------------------------------------
DELETE SCOR_DELEGUER
WHERE ISNULL(CODE_AGENCE, '') = ''

ALTER TABLE SCOR_DELEGUER
--DROP CONSTRAINT PK__SCOR_DEL__012FE90B7AC78219
DROP CONSTRAINT PK__SCOR_DEL__012FE90B35004B01

ALTER TABLE SCOR_DELEGUER
ALTER COLUMN CODE_AGENCE CHAR(10) NOT NULL

ALTER TABLE SCOR_DELEGUER
ADD CONSTRAINT PK__SCOR_DEL__012FE90B7AC78219 PRIMARY KEY (ID_SCOR_DELEGATION, ID_USER, CODE_AGENCE)

--LE BLOC SUIVANT NE DOIT PAS ETRE EXECUTER PLUS DE DEUX FOIS SUR LA BASE
UPDATE SCOR_DELEGUER
SET CODE_AGENCE = CONCAT('ML016', RIGHT(CODE_AGENCE, 5))

DELETE SCOR_DELEGUER
WHERE CODE_AGENCE NOT IN (SELECT CODE_AGENCE FROM SCOR_AGENCE)