USE [ScoringDB]
GO

ALTER TABLE SCOR_SEUIL_DELEGUATION
ADD ACTIF VARCHAR(2) NULL
go

ALTER TABLE SCOR_DELEGUER
ADD ACTIF VARCHAR(2) NULL
go

ALTER TABLE SCOR_DELEGATION
ADD ACTIF VARCHAR(2) NULL
go

ALTER TABLE SCOR_DOSSIER_SEUIL_CREDIT
ADD ACTIF VARCHAR(2) NULL
go

UPDATE SCOR_SEUIL_DELEGUATION
SET ACTIF = 'I'
go

UPDATE SCOR_DELEGUER
SET ACTIF = 'I'
go

UPDATE SCOR_DELEGATION
SET ACTIF = 'I'
go

UPDATE SCOR_DOSSIER_SEUIL_CREDIT
SET ACTIF = 'I'
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Selection_List_Seuil]    Script Date: 29/03/2023 19:20:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Selection_List_Seuil]
@CODE_BANQUE T_CODE_5 null
As
Begin
	if @CODE_BANQUE is null set @CODE_BANQUE='%'
	Select * from SCOR_SEUIL_DELEGUATION where CODE_BANQUE like @CODE_BANQUE 
	AND ACTIF = 'A' order by MAX_SCOR_SEUIL_DELEGUATION
End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Selection_List_Seuil_Specif]    Script Date: 29/03/2023 19:46:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Selection_List_Seuil_Specif]
@ID_SCOR_SEUIL_DELEGUATION int null,
@LIBELLE_SEUIL_DELEGUATION varchar(50) null,
@MAX_SCOR_SEUIL_DELEGUATION bigint null,
@MIN_SCOR_SEUIL_DELEGUATION bigint null,
@ValeurComparaison bigint null,
@Intervalle varchar(50) null
As
Begin
	if @ID_SCOR_SEUIL_DELEGUATION is not null 

	BEGIN

	Select * from SCOR_SEUIL_DELEGUATION where ID_SCOR_SEUIL_DELEGUATION=@ID_SCOR_SEUIL_DELEGUATION 
	AND ACTIF = 'A'

	END

	if @LIBELLE_SEUIL_DELEGUATION is not null

	BEGIN

	Select * from SCOR_SEUIL_DELEGUATION where LIBELLE_SEUIL_DELEGUATION like '%'+@LIBELLE_SEUIL_DELEGUATION+'%' 
	AND ACTIF = 'A'

	END

	if @MAX_SCOR_SEUIL_DELEGUATION is not null

	BEGIN

	Select * from SCOR_SEUIL_DELEGUATION where MAX_SCOR_SEUIL_DELEGUATION = @MAX_SCOR_SEUIL_DELEGUATION
	AND ACTIF = 'A'

	END
 
	if @MIN_SCOR_SEUIL_DELEGUATION is not null

	BEGIN

	Select * from SCOR_SEUIL_DELEGUATION where MIN_SCOR_SEUIL_DELEGUATION = @MIN_SCOR_SEUIL_DELEGUATION  
	AND ACTIF = 'A'

	END

if @ValeurComparaison is not null
begin
	if @Intervalle = 'FF' 
	Select * from SCOR_SEUIL_DELEGUATION where MIN_SCOR_SEUIL_DELEGUATION <= @ValeurComparaison 
	And MAX_SCOR_SEUIL_DELEGUATION >= @ValeurComparaison AND ACTIF = 'A'
	if @Intervalle = 'FO' 
	Select * from SCOR_SEUIL_DELEGUATION where MIN_SCOR_SEUIL_DELEGUATION <= @ValeurComparaison 
	And MAX_SCOR_SEUIL_DELEGUATION > @ValeurComparaison AND ACTIF = 'A'
	if @Intervalle = 'OF' 
	Select * from SCOR_SEUIL_DELEGUATION where MIN_SCOR_SEUIL_DELEGUATION < @ValeurComparaison 
	And MAX_SCOR_SEUIL_DELEGUATION >= @ValeurComparaison AND ACTIF = 'A'
	if @Intervalle = 'OO' 
	Select * from SCOR_SEUIL_DELEGUATION where MIN_SCOR_SEUIL_DELEGUATION < @ValeurComparaison 
	And MAX_SCOR_SEUIL_DELEGUATION > @ValeurComparaison AND ACTIF = 'A' 
End

End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Specif_SchemaDelegataire_A]    Script Date: 29/03/2023 19:50:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Specif_SchemaDelegataire_A]
@ID_SCOR_SEUIL_DELEGUATION int,
@LIBELLE_SCOR_DELEGATION varchar(50)
As
Begin

	Select 
	DEL.ID_SCOR_DELEGATION ID_LIGNE
	,DEL.ID_SCOR_SEUIL_DELEGUATION
	,DEL.LIBELLE_SCOR_DELEGATION
	from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU--, SCOR_DELEGUER DER
	where 
	DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
	AND DEL.ID_SCOR_SEUIL_DELEGUATION = @ID_SCOR_SEUIL_DELEGUATION
	AND DEL.LIBELLE_SCOR_DELEGATION= @LIBELLE_SCOR_DELEGATION
	AND DEL.ACTIF = 'A' AND SEU.ACTIF = 'A'
	--AND DER.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE)

End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Specif_SchemaDelegataire_B]    Script Date: 29/03/2023 19:52:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[PS_SCOR_Specif_SchemaDelegataire_B]

@bloc int,
@ID_SCOR_SEUIL_DELEGUATION int,
@ID_Dossier varchar(10),
@CODE_BANQUE varchar(50)
As
Begin
IF @bloc = -1
	BEGIN
			SELECT * FROM SCOR_DELEGATION , SCOR_SEUIL_DELEGUATION
	END
	IF @bloc = 0
	BEGIN
			Select 
			DEL.ID_SCOR_DELEGATION 
			,DEL.ID_SCOR_SEUIL_DELEGUATION
			,DEL.LIBELLE_SCOR_DELEGATION
			from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU--, SCOR_DELEGUER DER
			where 
			DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
			AND DEL.ID_SCOR_SEUIL_DELEGUATION = @ID_SCOR_SEUIL_DELEGUATION
			and DEL.ID_SCOR_DELEGATION in(select ID_SCOR_DELEGATION from SCOR_DELEGUER where CODE_AGENCE in ( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE))
			--AND DEL.LIBELLE_SCOR_DELEGATION= @LIBELLE_SCOR_DELEGATION
			--AND DER.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE)
			AND DEL.ACTIF = 'A' AND SEU.ACTIF = 'A'
	END
	IF @bloc = 1
	BEGIN
		Declare @id_scor_seul as int=0;

		select @id_scor_seul=ID_SCOR_SEUIL_DELEGUATION from SCOR_DOSSIER_SEUIL_CREDIT where Ltrim(Rtrim(ID_DOSSIER))=Ltrim(Rtrim(@ID_Dossier))

		Select 
		DEL.ID_SCOR_DELEGATION 
		,DEL.ID_SCOR_SEUIL_DELEGUATION
		,DEL.LIBELLE_SCOR_DELEGATION
		from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU--, SCOR_DELEGUER DER
		where 
		DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
		AND DEL.ID_SCOR_SEUIL_DELEGUATION = @id_scor_seul
		and DEL.ID_SCOR_DELEGATION in(select ID_SCOR_DELEGATION from SCOR_DELEGUER where CODE_AGENCE in ( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE))
		--AND DEL.LIBELLE_SCOR_DELEGATION= @LIBELLE_SCOR_DELEGATION
		--AND DER.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE)
		AND DEL.ACTIF = 'A' AND SEU.ACTIF = 'A'

	END


	

End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Supp_SchemaDelegataire_A]    Script Date: 29/03/2023 19:53:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Supp_SchemaDelegataire_A]
@ID_SCOR_DELEGATION int
,@CODE_AGENCE char(10)
As
Begin
	--DELETE FROM SCOR_DELEGUER
 --   WHERE 
	--ID_SCOR_DELEGATION=@ID_SCOR_DELEGATION
	--AND CODE_AGENCE=@CODE_AGENCE

	UPDATE SCOR_DELEGUER
	SET ACTIF = 'I'
	WHERE ID_SCOR_DELEGATION=@ID_SCOR_DELEGATION
	AND CODE_AGENCE=@CODE_AGENCE

End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Supp_SchemaDelegataire_B]    Script Date: 29/03/2023 19:55:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Supp_SchemaDelegataire_B]
@ID_SCOR_DELEGATION int
,@ID_USER char(6)
As
Begin
	--DELETE FROM SCOR_DELEGUER
 --     WHERE 
	--  ID_SCOR_DELEGATION=@ID_SCOR_DELEGATION
	--  AND ID_USER=@ID_USER

	  UPDATE SCOR_DELEGUER
	SET ACTIF = 'I'
	WHERE ID_SCOR_DELEGATION=@ID_SCOR_DELEGATION
	AND ID_USER=@ID_USER
End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Supp_SchemaDelegataire_C1]    Script Date: 29/03/2023 19:56:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Supp_SchemaDelegataire_C1]
@ID_SCOR_DELEGATION int
As
Begin
	--DELETE FROM SCOR_DELEGUER
 --     WHERE 
	--  ID_SCOR_DELEGATION=@ID_SCOR_DELEGATION

	--DELETE FROM SCOR_DELEGATION
 --     WHERE 
	--  ID_SCOR_DELEGATION=@ID_SCOR_DELEGATION

	  UPDATE SCOR_DELEGUER
	  SET ACTIF = 'I'
	  WHERE ID_SCOR_DELEGATION = @ID_SCOR_DELEGATION

	  UPDATE SCOR_DELEGATION
	  SET ACTIF = 'I'
	  WHERE ID_SCOR_DELEGATION = @ID_SCOR_DELEGATION
	  
End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_A]    Script Date: 29/03/2023 19:59:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_A]
@CODE_BANQUE varchar(50)
As
Begin 

	Select 
	DEL.ID_SCOR_DELEGATION ID_LIGNE
	, DEL.LIBELLE_SCOR_DELEGATION NOM_DELEG
	, Convert(varchar(50),SEU.MIN_SCOR_SEUIL_DELEGUATION) + ' à ' + Convert(varchar(50),SEU.MAX_SCOR_SEUIL_DELEGUATION) SEUIL
	from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU, SCOR_DELEGUER DER
	where 
	DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
	AND DER.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE)
	AND DEL.ACTIF = 'A' AND SEU.ACTIF = 'A' AND DER.ACTIF = 'A'

End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_A1]    Script Date: 29/03/2023 20:01:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_A1]
@CODE_BANQUE varchar(50)
As
Begin

	Select 
	DEL.ID_SCOR_DELEGATION ID_LIGNE
	, DEL.LIBELLE_SCOR_DELEGATION NOM_DELEG
	, Convert(varchar(50),SEU.MIN_SCOR_SEUIL_DELEGUATION) + ' à ' + Convert(varchar(50),SEU.MAX_SCOR_SEUIL_DELEGUATION) SEUIL
	,SEU.MAX_SCOR_SEUIL_DELEGUATION MAXSEUIL
	,SEU.MIN_SCOR_SEUIL_DELEGUATION MINSEUIL
	--from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU, SCOR_DELEGUER DER
	--where 
	--DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
	--AND DEL.ID_SCOR_DELEGATION = DER.ID_SCOR_DELEGATION
	--AND DER.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE='BDU01')
	
	from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU
	where 
	DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
	AND DEL.ID_SCOR_DELEGATION in (select ID_SCOR_DELEGATION from SCOR_DELEGUER where
	 CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE))
	 AND DEL.ACTIF = 'A' AND SEU.ACTIF = 'A'

End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_B]    Script Date: 29/03/2023 20:02:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_B]
@ID_LIGNE int
,@CODE_BANQUE varchar(50)
As
Begin

	Select 
	UT.ID_USER ID_USER, UT.NOM_USER NOM_USER, UT.PRENOM_USER PRENOM_USER, UT.PRENOM_USER+' '+UT.NOM_USER NOMCOMPLET
	from SCOR_UTILISATEUR UT--, SCOR_DELEGUER DER
	where 
	
	 UT.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE)
	AND ID_USER in(select ID_USER from SCOR_DELEGUER where  ID_SCOR_DELEGATION=@ID_LIGNE and CODE_AGENCE in ( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE) AND ACTIF = 'A')


End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_C]    Script Date: 29/03/2023 20:04:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_C]
@ID_LIGNE int
,@CODE_BANQUE varchar(50)
As
Begin

	Select 
	AG.CODE_AGENCE CODE_AGENCE, AG.NOM_AGENCE NOMAGENCE, AG.GUICHET_AGENCE GUICHET_AGENCE, AG.CODE_BANQUE CODE_BANQUE
	from SCOR_AGENCE AG--, SCOR_DELEGUER DER
	where 
	CODE_AGENCE in(select  CODE_AGENCE from SCOR_DELEGUER where
	CODE_BANQUE= @CODE_BANQUE
	AND ID_SCOR_DELEGATION=@ID_LIGNE
	AND ACTIF = 'A')

End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_Liste]    Script Date: 29/03/2023 20:05:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER Procedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_Liste]
@ID_LIGNE int
,@CODE_BANQUE varchar(50)
As
Begin

	Select 
	UT.ID_USER ID_USER, UT.NOM_USER NOM_USER, UT.PRENOM_USER PRENOM_USER, UT.PRENOM_USER+' '+UT.NOM_USER NOMCOMPLET,UT.EMAIL_USER EMAIL_USER
	from SCOR_UTILISATEUR UT--, SCOR_DELEGUER DER0
	where 
	 UT.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE)
	AND ID_USER in(select ID_USER from SCOR_DELEGUER where  ID_SCOR_DELEGATION=@ID_LIGNE and CODE_AGENCE in ( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE) AND ACTIF = 'A')


End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_A]    Script Date: 30/03/2023 10:03:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_A]
@LIBELLE_SEUIL_DELEGUATION varchar(100)
,@MAX_SCOR_SEUIL_DELEGUATION bigint
,@MIN_SCOR_SEUIL_DELEGUATION bigint
,@CODE_BANQUE varchar(50)
As
Begin
declare @ID_SCOR_SEUIL_DELEGUATION int =0
SELECT @ID_SCOR_SEUIL_DELEGUATION=MAX(ISNULL(ID_SCOR_SEUIL_DELEGUATION,0)) FROM SCOR_SEUIL_DELEGUATION 
SET @ID_SCOR_SEUIL_DELEGUATION=ISNULL(@ID_SCOR_SEUIL_DELEGUATION,0)+1

	if (select count(*) from SCOR_BANQUE where CODE_BANQUE = @CODE_BANQUE) > 0
	/*AND NOT EXISTS (SELECT * from SCOR_SEUIL_DELEGUATION WHERE MAX_SCOR_SEUIL_DELEGUATION = @MAX_SCOR_SEUIL_DELEGUATION
	AND MIN_SCOR_SEUIL_DELEGUATION = @MIN_SCOR_SEUIL_DELEGUATION AND CODE_BANQUE = @CODE_BANQUE)*/
	Begin
		INSERT INTO SCOR_SEUIL_DELEGUATION
			   (ID_SCOR_SEUIL_DELEGUATION, LIBELLE_SEUIL_DELEGUATION
			   , MAX_SCOR_SEUIL_DELEGUATION, MIN_SCOR_SEUIL_DELEGUATION,CODE_BANQUE, ACTIF)
		 VALUES
			   (@ID_SCOR_SEUIL_DELEGUATION, @LIBELLE_SEUIL_DELEGUATION
			   ,@MAX_SCOR_SEUIL_DELEGUATION, @MIN_SCOR_SEUIL_DELEGUATION, @CODE_BANQUE, 'A')
	End
End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_B]    Script Date: 29/03/2023 20:11:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_B]
@LIBELLE_SCOR_DELEGATION varchar(50)
,@ID_SCOR_SEUIL_DELEGUATION int
As
Begin
declare @ID_SCOR_DELEGATION int =0
SELECT @ID_SCOR_DELEGATION=MAX(ISNULL(ID_SCOR_DELEGATION,0)) FROM SCOR_DELEGUER
SET @ID_SCOR_DELEGATION=ISNULL(@ID_SCOR_DELEGATION,0)+1

	INSERT INTO [dbo].[SCOR_DELEGATION]
           ([ID_SCOR_DELEGATION]
           ,[LIBELLE_SCOR_DELEGATION]
           ,[ID_SCOR_SEUIL_DELEGUATION]
		   ,ACTIF)
     VALUES
           (@ID_SCOR_DELEGATION
           ,@LIBELLE_SCOR_DELEGATION
           ,@ID_SCOR_SEUIL_DELEGUATION
		   ,'A')

	
End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_C]    Script Date: 29/03/2023 20:12:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_C]
@ID_SCOR_DELEGATION int
,@ID_USER char(6)
,@CODE_AGENCE char(10)
As
Begin
	INSERT INTO SCOR_DELEGUER
           (ID_SCOR_DELEGATION,ID_USER 
		    ,CODE_AGENCE, DATEDELEGUER, ACTIF)
     VALUES
           (@ID_SCOR_DELEGATION, @ID_USER
           ,@CODE_AGENCE, GETDATE(), 'A')
End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Mod_SchemaDelegataire_A]    Script Date: 29/03/2023 20:14:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Mod_SchemaDelegataire_A]
@LIBELLE_SEUIL_DELEGUATION varchar(100)
,@MAX_SCOR_SEUIL_DELEGUATION bigint
,@MIN_SCOR_SEUIL_DELEGUATION bigint
,@ID_SCOR_SEUIL_DELEGUATION int
As
Begin
	UPDATE SCOR_SEUIL_DELEGUATION
   SET 
      LIBELLE_SEUIL_DELEGUATION = @LIBELLE_SEUIL_DELEGUATION
      ,MAX_SCOR_SEUIL_DELEGUATION = @MAX_SCOR_SEUIL_DELEGUATION
      ,MIN_SCOR_SEUIL_DELEGUATION = @MIN_SCOR_SEUIL_DELEGUATION
 WHERE ID_SCOR_SEUIL_DELEGUATION = @ID_SCOR_SEUIL_DELEGUATION
 AND ACTIF = 'A'
End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_delete_SchemaDelegataire_C]    Script Date: 29/03/2023 20:16:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER proc [dbo].[PS_SCOR_delete_SchemaDelegataire_C]
@idLigne bigint
as
begin 
	--delete from SCOR_DELEGUER where ID_SCOR_DELEGATION=@idLigne
	--delete FROM SCOR_DELEGATION where ID_SCOR_DELEGATION=@idLigne

	UPDATE SCOR_DELEGUER
	SET ACTIF = 'I'
	WHERE ID_SCOR_DELEGATION = @idLigne

	UPDATE SCOR_DELEGATION
	SET ACTIF = 'I'
	WHERE ID_SCOR_DELEGATION = @idLigne
end
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_A1]    Script Date: 30/03/2023 11:57:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Tableau_SchemaDelegataire_A1]
@CODE_BANQUE varchar(50)
As
Begin

	Select 
	DEL.ID_SCOR_DELEGATION ID_LIGNE
	, DEL.LIBELLE_SCOR_DELEGATION NOM_DELEG
	, Convert(varchar(50),SEU.MIN_SCOR_SEUIL_DELEGUATION) + ' à ' + Convert(varchar(50),SEU.MAX_SCOR_SEUIL_DELEGUATION) SEUIL
	,SEU.MAX_SCOR_SEUIL_DELEGUATION MAXSEUIL
	,SEU.MIN_SCOR_SEUIL_DELEGUATION MINSEUIL
	--from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU, SCOR_DELEGUER DER
	--where 
	--DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
	--AND DEL.ID_SCOR_DELEGATION = DER.ID_SCOR_DELEGATION
	--AND DER.CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE='BDU01')
	
	from SCOR_DELEGATION DEL, SCOR_SEUIL_DELEGUATION SEU
	where 
	DEL.ID_SCOR_SEUIL_DELEGUATION = SEU.ID_SCOR_SEUIL_DELEGUATION
	AND DEL.ID_SCOR_DELEGATION in (select ID_SCOR_DELEGATION from SCOR_DELEGUER where
	 CODE_AGENCE IN( SELECT CODE_AGENCE FROM SCOR_AGENCE WHERE CODE_BANQUE=@CODE_BANQUE) AND ACTIF = 'A')
	 AND DEL.ACTIF = 'A' AND SEU.ACTIF = 'A'

End
go

/****** Object:  StoredProcedure [dbo].[PS_SCOR_INSERT_CREDIT_DOSSIER]    Script Date: 30/03/2023 12:13:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_INSERT_CREDIT_DOSSIER]
@ID_SCOR_SEUIL_DELEGUATION int,
@ID_DOSSIER char(8)
As
Begin
	BEGIN TRY
		Declare @verif int 
		SELECT @verif=Count(ID_SCOR_SEUIL_DELEGUATION) FROM SCOR_DOSSIER_SEUIL_CREDIT
		Where ID_DOSSIER=@ID_DOSSIER

		if @verif= 0 begin
		INSERT INTO SCOR_DOSSIER_SEUIL_CREDIT
		(ID_SCOR_SEUIL_DELEGUATION, ID_DOSSIER, DATE_CHOIX_CREDIT, ACTIF)
		VALUES (@ID_SCOR_SEUIL_DELEGUATION, @ID_DOSSIER, getdate(), 'A')
		end
		else begin
			if @verif= 1 begin
				if @ID_SCOR_SEUIL_DELEGUATION= 0 begin
					delete from SCOR_DOSSIER_SEUIL_CREDIT
					Where ID_DOSSIER=@ID_DOSSIER
				end
				else begin
					Update SCOR_DOSSIER_SEUIL_CREDIT SET 
					ID_SCOR_SEUIL_DELEGUATION=@ID_SCOR_SEUIL_DELEGUATION,DATE_CHOIX_CREDIT=getdate()
					Where ID_DOSSIER=@ID_DOSSIER
				end
			end
		end 
		

	END TRY
	BEGIN CATCH
			  SELECT   CONCAT( 'ErrorNumber: ',ERROR_NUMBER(),', '  
			  ,'ErrorSeverity: ',ERROR_SEVERITY(),', ' 
			  ,'ErrorState: ',ERROR_STATE(),', ' 
			  ,'ErrorLine: ',ERROR_LINE(),', ' 
			  ,'ErrorProcedure: ',ERROR_PROCEDURE(),', ' 
			  ,'ErrorMessage: ',ERROR_MESSAGE(),' ')
				
	END CATCH
	 

End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_B]    Script Date: 30/03/2023 12:23:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_B]
@LIBELLE_SCOR_DELEGATION varchar(50)
,@ID_SCOR_SEUIL_DELEGUATION int
As
Begin

declare @ID_SCOR_DELEGATION int =0
set @ID_SCOR_DELEGATION=ISNULL((SELECT MAX(ISNULL(ID_SCOR_DELEGATION,0)) FROM SCOR_DELEGUER),0)
SET @ID_SCOR_DELEGATION=ISNULL(@ID_SCOR_DELEGATION,0)+1 

	INSERT INTO [dbo].[SCOR_DELEGATION]
           ([ID_SCOR_DELEGATION]
           ,[LIBELLE_SCOR_DELEGATION]
           ,[ID_SCOR_SEUIL_DELEGUATION]
		   ,ACTIF)
     VALUES
           (@ID_SCOR_DELEGATION
           ,@LIBELLE_SCOR_DELEGATION
           ,@ID_SCOR_SEUIL_DELEGUATION
		   ,'A')

	
End
GO

/****** Object:  StoredProcedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_B]    Script Date: 30/03/2023 12:23:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[PS_SCOR_Insert_SchemaDelegataire_B]
@LIBELLE_SCOR_DELEGATION varchar(50)
,@ID_SCOR_SEUIL_DELEGUATION int
As
Begin

declare @ID_SCOR_DELEGATION int =0
set @ID_SCOR_DELEGATION=ISNULL((SELECT MAX(ISNULL(ID_SCOR_DELEGATION,0)) FROM SCOR_DELEGATION),0)
SET @ID_SCOR_DELEGATION=ISNULL(@ID_SCOR_DELEGATION,0)+1 

	INSERT INTO [dbo].[SCOR_DELEGATION]
           ([ID_SCOR_DELEGATION]
           ,[LIBELLE_SCOR_DELEGATION]
           ,[ID_SCOR_SEUIL_DELEGUATION]
		   ,ACTIF)
     VALUES
           (@ID_SCOR_DELEGATION
           ,@LIBELLE_SCOR_DELEGATION
           ,@ID_SCOR_SEUIL_DELEGUATION
		   ,'A')

	
End
GO