USE [ScoringDB]
GO
if Object_id('PS_CHARGEMENT_CSV_ENCOURS','P') is not null 
Drop PROCEDURE PS_CHARGEMENT_CSV_ENCOURS
GO
CREATE PROCEDURE [dbo].[PS_CHARGEMENT_CSV_ENCOURS]
	@A as Varchar(max),
	@B as Varchar(max),
	@C as Varchar(max),
	@D as Varchar(max),
	@E as Varchar(max),
	@F as Varchar(max),
	@G as Varchar(max),
	@H as Varchar(max),
	@I as Varchar(max)
AS
BEGIN
 
	DECLARE @ID_DOSSIER VARCHAR(20)

	SELECT @ID_DOSSIER=CONVERT(INT,MAX(CONVERT(INT,ISNULL(ID_DOSSIER,0)))) 
	FROM SCOR_DOSSIER 
	WHERE ID_SCORING IN(SELECT ID_SCORING FROM SCOR_CONTREPARTIE WHERE LTRIM(RTRIM([ETCIV_MATRICULE]))=SUBSTRING(LTRIM(RTRIM(@B)),1,6))
		
	DECLARE @NBRE INT=0

	SELECT @NBRE=COUNT(*) 
	FROM LESENCOURSBMS 
	WHERE LTRIM(RTRIM(ID_DOSSIER))=LTRIM(RTRIM(@ID_DOSSIER)) 
	AND LTRIM(RTRIM([CODE]))=LTRIM(RTRIM(@A)) 
	AND LTRIM(RTRIM([IDCLIENT]))=LTRIM(RTRIM(@B)) 
	AND LTRIM(RTRIM([COMPTE]))=LTRIM(RTRIM(@E))
	
	IF @ID_DOSSIER IS NOT NULL AND @ID_DOSSIER <> ''
	BEGIN
		IF @NBRE=0
		BEGIN
		
			INSERT INTO LESENCOURSBMS (
				[CODE]
				,[ID_DOSSIER]
				,[IDCLIENT]
				,[INTITULE]
				,[LIBELLE]
				,[COMPTE]
				,[SOLDE]
				,[AUTORISATION]
				,[ECHEANCE]
				,[DEVISE]
			)
			VALUES (
				@A
				,@ID_DOSSIER
				,@B
				,@C
				,@D
				,@E
				,@F
				,@G
				,@H
				,@I
			)

		END
		ELSE
		BEGIN

			UPDATE [DBO].[LESENCOURSBMS]
			SET [INTITULE] = @C
			,[LIBELLE] = @D
			,[SOLDE] = @F
			,[AUTORISATION] =@G
			,[ECHEANCE] = @H
			,[DEVISE] = @I
			WHERE LTRIM(RTRIM(ID_DOSSIER))=LTRIM(RTRIM(@ID_DOSSIER)) 
			AND  LTRIM(RTRIM([CODE]))=LTRIM(RTRIM(@A)) 
			AND LTRIM(RTRIM([IDCLIENT]))=LTRIM(RTRIM(@B)) 
			AND  LTRIM(RTRIM([COMPTE]))=LTRIM(RTRIM(@E))

		END	
	END
		
END