use ScoringDB
GO
if OBJECT_ID('PS_SCOR_MAJ_AUTO_REF_ENTREP','P') is not null 
DROP PROCEDURE [dbo].[PS_SCOR_MAJ_AUTO_REF_ENTREP]
GO
CREATE PROCEDURE [dbo].[PS_SCOR_MAJ_AUTO_REF_ENTREP]
	@BANQUE_CODE T_CODE_5,
	@DATA_LOCATION VARCHAR(MAX)
AS
BEGIN

	DECLARE @LOAD_DCLTS_SUCCESS BIT = 1, @LOAD_DCPTS_SUCCESS BIT = 1

	TRUNCATE TABLE SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE;
	TRUNCATE TABLE SCOR_DONNEES_COMPTABLES_ENTREPRISE;

	DECLARE @SQL VARCHAR(MAX);

	BEGIN TRY  
		SET @SQL = 'BULK INSERT SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE
		FROM ''' + CONCAT(@DATA_LOCATION, '\', @BANQUE_CODE, '_references_donnees_clients.csv') + '''
		WITH
		(
			FIRSTROW = 2,
			FIELDTERMINATOR = '';'',
			ROWTERMINATOR = ''\n'',
			TABLOCK
		)';
		EXEC (@SQL);
	END TRY  
	BEGIN CATCH  
		IF (SELECT COUNT(*) FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE) = 0
		BEGIN
			SET @LOAD_DCLTS_SUCCESS = 0
			PRINT 'ECHEC TOTAL DE CHARGEMENT DES DONNEES CLIENTS';
		END
		ELSE
		BEGIN
			PRINT 'LE CHARGEMENT DES DONNEES CLIENTS NE S''EST PAS EFFECTUE COMPLETEMENT';
		END
	END CATCH 

	BEGIN TRY 
		SET @SQL = 'BULK INSERT SCOR_DONNEES_COMPTABLES_ENTREPRISE
		FROM ''' + CONCAT(@DATA_LOCATION, '\', @BANQUE_CODE, '_references_donnees_comptables.csv') + '''
		WITH
		(
			FIRSTROW = 2,
			FIELDTERMINATOR = '';'',
			ROWTERMINATOR = ''\n'',
			TABLOCK
		)';
	EXEC (@SQL);
	END TRY  
	BEGIN CATCH  
		IF (SELECT COUNT(*) FROM SCOR_DONNEES_COMPTABLES_ENTREPRISE) = 0
		BEGIN
			SET @LOAD_DCPTS_SUCCESS = 0
			PRINT 'ECHEC TOTAL DE CHARGEMENT DES DONNEES COMPTABLES';
		END
		ELSE
		BEGIN
			PRINT 'LE CHARGEMENT DES DONNEES COMPTABLES NE S''EST PAS EFFECTUE COMPLETEMENT';
		END
	END CATCH	

	DECLARE @CODE_BANQUE T_CODE_5, 
		@ETCIV_MATRICULE T_CODE_12,
		@ETCIV_NOMREDUIT VARCHAR(MAX),
		@CODE_AGENCE T_CODE_10,
		@CODE_GUICHET T_CODE_5,
		@ADRESSE VARCHAR(MAX),
		@VILLE T_LIBEL_MOYEN_35,
		@PAYS_ISO T_LIBEL_MOYEN_35,
		@NUM_IDENTIF_FISCAL T_LIBEL_MOYEN_35,
		@TYPE_CLIENT T_LIBEL_MOYEN_35,
		@SECTEUR_ACTIVITE T_LIBEL_MOYEN_35,
		@STATUT_JURIDIQUE T_LIBEL_MOYEN_35,
		----------------------------------
		@TYPE_CPTE T_LIBEL_MOYEN_35,
		@CPTEAUXIL_NUMCPT T_CODE_12,
		@INTITULE_CPTE T_LIBEL_MOYEN_35,
		@SOLDE T_MONTANT_DEVISE,
		@AUTORIS_DECOUVERT T_MONTANT_DEVISE,
		@ECHEANCE_AUTORIS T_LIBEL_MOYEN_35,
		@CODE_DEVISE T_CODE_3;

	

	DECLARE @I INT = 1, @MAX INT;

	IF @LOAD_DCLTS_SUCCESS = 1
	BEGIN
		DECLARE @NOW DATETIME--, @PAYS VARCHAR(35);
		-- 1/ TRAITEMENT DES DONNEES SIGNALETIQUES ENTREPRISE --
		IF OBJECT_ID('SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE') IS NOT NULL
		BEGIN
			DROP TABLE SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE;
		END
	
		IF OBJECT_ID('SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_INSERT') IS NOT NULL
		BEGIN
			DROP TABLE SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_INSERT;
		END

		-- RECUPERATION DES DONNEES SIGNALETIQUES ENTREPRISE POUR MISE A JOUR
		SELECT ROW_NUMBER() OVER(ORDER BY SC.ETCIV_MATRICULE) ID, DS.* 
		INTO SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE
		FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE DS
		JOIN SCOR_CONTREPARTIE SC ON (
			replace(rtrim(ltrim(SC.ETCIV_MATRICULE)),' ','') = replace(rtrim(ltrim(DS.ETCIV_MATRICULE)),' ','') 
			AND replace(rtrim(ltrim(SC.CODE_AGENCE)),' ','')  = replace(rtrim(ltrim(CONCAT(@BANQUE_CODE, DS.CODE_GUICHET))),' ','') 
		)
		JOIN SCOR_AGENCE SA ON (
			replace(rtrim(ltrim(SA.CODE_BANQUE)),' ','')  = replace(rtrim(ltrim(DS.CODE_BANQUE)),' ','') 
			AND replace(rtrim(ltrim(SA.CODE_AGENCE)),' ','') = replace(rtrim(ltrim(CONCAT(@BANQUE_CODE, DS.CODE_GUICHET))),' ','') 
			AND replace(rtrim(ltrim(SC.CODE_AGENCE)),' ','') = replace(rtrim(ltrim(SA.CODE_AGENCE)),' ','') 
			AND replace(rtrim(ltrim(SA.CODE_BANQUE)),' ','') = replace(rtrim(ltrim(@BANQUE_CODE)),' ','') 
		);

		-- RECUPERATION DES DONNEES SIGNALETIQUES ENTREPRISE POUR CREATION
		SELECT ROW_NUMBER() OVER(ORDER BY DS.ETCIV_MATRICULE) ID, DS.*
		INTO SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_INSERT
		FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE DS
		WHERE replace(rtrim(ltrim(CONCAT(DS.CODE_BANQUE, DS.CODE_GUICHET))),' ','') NOT IN (
			SELECT replace(rtrim(ltrim(CONCAT(UP.CODE_BANQUE, UP.CODE_GUICHET))),' ','')
			FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE UP
		)
		AND CONCAT(DS.CODE_BANQUE, DS.CODE_GUICHET) IN (SELECT CODE_AGENCE FROM SCOR_AGENCE)

		-- PARTIE MODIICATIONS
		SELECT @MAX = COUNT(*) FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE;
	
		WHILE @I <= @MAX
		BEGIN
		
			SELECT @CODE_BANQUE = LTRIM(RTRIM(DSU.CODE_BANQUE)),
				@ETCIV_MATRICULE = LTRIM(RTRIM(DSU.ETCIV_MATRICULE)),
				@ETCIV_NOMREDUIT = LTRIM(RTRIM(DSU.ETCIV_NOMREDUIT)),
				@CODE_AGENCE = CONCAT(@BANQUE_CODE, LTRIM(RTRIM(DSU.CODE_GUICHET))),
				@CODE_GUICHET = LTRIM(RTRIM(DSU.CODE_GUICHET)),
				@ADRESSE = LTRIM(RTRIM(DSU.ADRESSE)),
				@VILLE = LTRIM(RTRIM(DSU.VILLE)),
				@PAYS_ISO = LTRIM(RTRIM(DSU.PAYS_ISO)),
				@NUM_IDENTIF_FISCAL = LTRIM(RTRIM(DSU.NUM_IDENTIF_FISCAL)),
				@TYPE_CLIENT= LTRIM(RTRIM(DSU.TYPE_CLIENT)),
				@SECTEUR_ACTIVITE = LTRIM(RTRIM(DSU.SECTEUR_CODE)),
				@STATUT_JURIDIQUE = REPLICATE('0', 2 - len(LTRIM(RTRIM(DSU.STATUT_CODE)))) + LTRIM(RTRIM(DSU.STATUT_CODE))
			FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE DSU
			WHERE ID = @I

			SET @NOW = (SELECT CONVERT (DATETIME, SYSDATETIME()));

			EXEC PS_CHARG_CONTREPARTIE_INS 
				@BLOCK = 1,
				@DATECHARGEMENT = @NOW,
				@IDUSER = '0',
				@CODE_AGENCE = @CODE_AGENCE,
				@MATRICULE = @ETCIV_MATRICULE,
				@NOM = @ETCIV_NOMREDUIT,
				@ADRESSE = @ADRESSE,
				@VILLE_RESIDENCE = @VILLE,
				@RCCM = '-',
				@SEGMENT_CLIENT = 'Segment()',
				@MOIS_ARRETE = @NOW,
				@MODE_ANALYSE = 'ENTEXI',
				@TYPE_ANAFI = 'Bilan Normal',
				@UNITE = 'Milier',
				@DEVISE = 'XOF',
				@CA = '0',
				@PAYS = @PAYS_ISO,
				@STATUT = @STATUT_JURIDIQUE,
				@ACTIVITE_BCEAO = '000 000', -- SECTEUR ACTIVITE SYSCOHADA
				@SECTEUR_ACTIVITE = @SECTEUR_ACTIVITE,
				@GROUPE = '',
				@BRANCHEACTIF = 'A1';

			SET @I = @I + 1;
		END
		-- / FIN PARTIE MODIFICATIONS

		SET @I = 1;

		-- PARTIE CREATIONS
		SELECT @MAX = COUNT(*) FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_INSERT;

		WHILE @I <= @MAX
		BEGIN

			SELECT @CODE_BANQUE = LTRIM(RTRIM(DSI.CODE_BANQUE)),
				@ETCIV_MATRICULE = LTRIM(RTRIM(DSI.ETCIV_MATRICULE)),
				@ETCIV_NOMREDUIT = LTRIM(RTRIM(DSI.ETCIV_NOMREDUIT)),
				@CODE_AGENCE = CONCAT(@BANQUE_CODE, LTRIM(RTRIM(DSI.CODE_GUICHET))),
				@CODE_GUICHET = LTRIM(RTRIM(DSI.CODE_GUICHET)),
				@ADRESSE = LTRIM(RTRIM(DSI.ADRESSE)),
				@VILLE = LTRIM(RTRIM(DSI.VILLE)),
				@PAYS_ISO = LTRIM(RTRIM(DSI.PAYS_ISO)),
				@NUM_IDENTIF_FISCAL = LTRIM(RTRIM(DSI.NUM_IDENTIF_FISCAL)),
				@TYPE_CLIENT= LTRIM(RTRIM(DSI.TYPE_CLIENT)),
				@SECTEUR_ACTIVITE = LTRIM(RTRIM(DSI.SECTEUR_CODE)),
				@STATUT_JURIDIQUE = REPLICATE('0', 2 - len(LTRIM(RTRIM(DSI.STATUT_CODE)))) + LTRIM(RTRIM(DSI.STATUT_CODE))
			FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_INSERT DSI
			WHERE ID = @I

			SET @NOW = (SELECT CONVERT (DATETIME, SYSDATETIME()));

			EXEC PS_CHARG_CONTREPARTIE_INS 
				@BLOCK = 0,
				@DATECHARGEMENT = @NOW,
				@IDUSER = '0',
				@CODE_AGENCE = @CODE_AGENCE,
				@MATRICULE = @ETCIV_MATRICULE,
				@NOM = @ETCIV_NOMREDUIT,
				@ADRESSE = @ADRESSE,
				@VILLE_RESIDENCE = @VILLE,
				@RCCM = '-',
				@SEGMENT_CLIENT = 'Segment()',
				@MOIS_ARRETE = @NOW,
				@MODE_ANALYSE = 'ENTEXI',
				@TYPE_ANAFI = 'Bilan Normal',
				@UNITE = 'Milier',
				@DEVISE = 'XOF',
				@CA = '0',
				@PAYS = @PAYS_ISO,
				@STATUT = @STATUT_JURIDIQUE,
				@ACTIVITE_BCEAO = '000 000', -- SECTEUR ACTIVITE SYSCOHADA
				@SECTEUR_ACTIVITE = @SECTEUR_ACTIVITE,
				@GROUPE = '',
				@BRANCHEACTIF = 'A1';

			SET @I = @I + 1;
		END
		-- / FIN PARTIE CREATIONS

		IF OBJECT_ID('SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE') IS NOT NULL
		BEGIN
			DROP TABLE SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_UPDATE;
		END
	
		IF OBJECT_ID('SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_INSERT') IS NOT NULL
		BEGIN
			DROP TABLE SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE_TO_INSERT;
		END

	END

	IF @LOAD_DCPTS_SUCCESS = 1
	BEGIN
		-- 2/ TRAITEMENT DES DONNEES COMPTABLES ENTREPRISE --
		--IF OBJECT_ID('SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_UPDATE') IS NOT NULL
		--BEGIN
		--	DROP TABLE SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_UPDATE;
		--END
	
		--IF OBJECT_ID('SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_INSERT') IS NOT NULL
		--BEGIN
		--	DROP TABLE SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_INSERT;
		--END

		IF OBJECT_ID('SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_USE') IS NOT NULL
		BEGIN
			DROP TABLE SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_USE;
		END

		/*-- RECUPERATION DES DONNEES COMPTABLES ENTREPRISE POUR MISE A JOUR
		--SELECT ROW_NUMBER() OVER(ORDER BY DC.ETCIV_MATRICULE) ID, DC.* 
		--INTO SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_UPDATE
		--FROM SCOR_DONNEES_COMPTABLES_ENTREPRISE DC
		--JOIN LESENCOURSBMS LE ON ( 
		--	CONVERT(CHAR(6), LE.CODE) = DC.TYPE_CPTE
		--	AND CONVERT(CHAR(6), LE.IDCLIENT) = DC.ETCIV_MATRICULE
		--	AND CONVERT(CHAR(12), LE.COMPTE) = DC.CPTEAUXIL_NUMCPT
		--)

		---- RECUPERATION DES DONNEES COMPTABLES ENTREPRISE POUR CREATION
		--SELECT ROW_NUMBER() OVER(ORDER BY DC.ETCIV_MATRICULE) ID, DC.*
		--INTO SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_INSERT
		--FROM SCOR_DONNEES_COMPTABLES_ENTREPRISE DC
		--WHERE CONCAT(DC.TYPE_CPTE, DC.ETCIV_MATRICULE, DC.CPTEAUXIL_NUMCPT) NOT IN (
		--	SELECT CONCAT(UP.TYPE_CPTE, UP.ETCIV_MATRICULE, UP.CPTEAUXIL_NUMCPT)
		--	FROM SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_UPDATE UP
		--)*/

		-- RECUPERATION DES DONNEES COMPTABLES ENTREPRISE
		SELECT ROW_NUMBER() OVER(ORDER BY DC.TYPE_CPTE, DC.ETCIV_MATRICULE, DC.CPTEAUXIL_NUMCPT) ID, DC.*
		INTO SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_USE
		FROM SCOR_DONNEES_COMPTABLES_ENTREPRISE DC
			
		SET @I = 1;

		-- PARTIE AJOUT & MODIFICATIONS
		SELECT @MAX = COUNT(*) FROM SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_USE;

		WHILE @I <= @MAX
		BEGIN
		
			SELECT --@CODE_BANQUE = DC.CODE_BANQUE,
				--@CODE_AGENCE = DC.CODE_AGENCE,
				@TYPE_CPTE = DC.TYPE_CPTE,
				@ETCIV_MATRICULE = DC.ETCIV_MATRICULE,
				@ETCIV_NOMREDUIT = DC.ETCIV_NOMREDUIT,
				@CPTEAUXIL_NUMCPT = DC.CPTEAUXIL_NUMCPT,
				@SOLDE = DC.SOLDE, 
				@INTITULE_CPTE = DC.INTITULE_CPTE,
				@AUTORIS_DECOUVERT = DC.AUTORIS_DECOUVERT,
				@ECHEANCE_AUTORIS = DC.ECHEANCE_AUTORIS,
				@CODE_DEVISE = DC.CODE_DEVISE
			FROM SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_USE DC
			WHERE ID = @I;

			EXEC PS_CHARGEMENT_CSV_ENCOURS
				@A = @TYPE_CPTE,
				@B = @ETCIV_MATRICULE,
				@C = @INTITULE_CPTE,
				@D = @ETCIV_NOMREDUIT,
				@E = @CPTEAUXIL_NUMCPT,
				@F = @SOLDE,
				@G = @AUTORIS_DECOUVERT,
				@H = @ECHEANCE_AUTORIS,
				@I = @CODE_DEVISE

			SET @I = @I + 1;
		END
		-- / FIN PARTIE AJOUT & MODIFICATIONS

		IF OBJECT_ID('SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_USE') IS NOT NULL
		BEGIN
			DROP TABLE SCOR_DONNEES_COMPTABLES_ENTREPRISE_TO_USE;
		END
	END

	

		update SCOR_CONTREPARTIE 
		set CA=0
		from SCOR_DOSSIER A, ANAFI_PARAMETRE B
		where SCOR_CONTREPARTIE.ID_SCORING=A.ID_SCORING
		and A.ID_DOSSIER=B.ID_DOSSIER
		and B.ID_PARAMETRE not in (select distinct C.ID_PARAMETRE from ANAFI_PARAMETRE_DETAIL C)
	
END
