USE ScoringDB
GO
IF OBJECT_ID('PS_SCOR_MAJ_AUTO_REF_BANQUES','P') IS NOT NULL 
DROP PROCEDURE PS_SCOR_MAJ_AUTO_REF_BANQUES
GO

CREATE PROCEDURE [dbo].[PS_SCOR_MAJ_AUTO_REF_BANQUES]
AS
BEGIN
	
	IF OBJECT_ID('SCOR_BANQUES_TMP') IS NOT NULL
	BEGIN
		DROP TABLE SCOR_BANQUES_TMP;
	END

	-- RECUPERATION DES DONNEES DES CODES BANQUES ET REPERTOIRES DE RECUPERATION DES FICHIERS DE DONNEES
	SELECT ROW_NUMBER() OVER(ORDER BY SB.CODE_BANQUE) ID, SB.CODE_BANQUE, SB.REPERTOIRE_DONNEES 
	INTO SCOR_BANQUES_TMP
	FROM SCOR_BANQUE SB
	WHERE ISNULL(CODE_BANQUE, '') <> ''
	AND ISNULL(REPERTOIRE_DONNEES, '') <> ''

	DECLARE @MAX INT, @I INT

	SELECT @MAX = COUNT(*) FROM SCOR_BANQUES_TMP;

	SET @I = 1
	
	WHILE @I <= @MAX
	BEGIN
		
		DECLARE @CODE_BANQUE T_CODE_5
		DECLARE @REPERTOIRE_DONNEES VARCHAR(MAX)

		SELECT @CODE_BANQUE = LTRIM(RTRIM(CODE_BANQUE)),
			@REPERTOIRE_DONNEES = LTRIM(RTRIM(REPERTOIRE_DONNEES))
		FROM SCOR_BANQUES_TMP 
		WHERE ID = @I

		EXEC PS_SCOR_MAJ_AUTO_REF_ENTREP @CODE_BANQUE, @REPERTOIRE_DONNEES

		SET @I = @I + 1;
	END

	IF OBJECT_ID('SCOR_BANQUES_TMP') IS NOT NULL
	BEGIN
		DROP TABLE SCOR_BANQUES_TMP;
	END

END