USE [ScoringDB]
GO

/****** Object:  StoredProcedure [dbo].[PS_VSCOR_CONTREPARTIE_MOD]    Script Date: 28/02/2023 21:22:03 ******/
DROP PROCEDURE [dbo].[PS_VSCOR_CONTREPARTIE_MOD]
GO

/****** Object:  StoredProcedure [dbo].[PS_VSCOR_CONTREPARTIE_MOD]    Script Date: 28/02/2023 21:22:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE  procedure [dbo].[PS_VSCOR_CONTREPARTIE_MOD]
	@block as int,
    @ID_SCORING T_CODE_12,
	@ETCIV_MATRICULE T_CODE_12,
	@ETCIV_NOMREDUIT varchar(max),
	@ETCIV_ADRESSE varchar(max),
	@ETCIV_VILLE_RESIDENCE T_LIBEL_MOYEN_35 ,
	@PAYS T_LIBEL_MOYEN_35 ,
	@SEGMENT_CLIENT T_LIBEL_MOYEN_35 ,
	@CODE_AGENCE varchar(10) ,
	@CA T_NUMERIQUE_GRAND ,
	@DEVISE T_CODE_GRAND  ,
	@RCCM T_CODE_GRAND  ,
	@SECTEUR_D_ACTIVITE  T_LIBEL_MOYEN_45 ,
	@ACTIVITE_BCEAO  T_LIBEL_MOYEN_45,
	@STATUT T_LIBEL_LONG_120 ,
	@MODE_ANALYSE T_LIBEL_MOYEN_35  ,
	@UNITE T_CODE_GRAND,
	@GROUPE varchar(max),
	@BRANCHE_ACTIVITE varchar(max)
	
 as
begin
IF @block=1
begin
	UPDATE SCOR_CONTREPARTIE SET
	      ETCIV_NOMREDUIT = @ETCIV_NOMREDUIT,
	      ETCIV_ADRESSE = @ETCIV_ADRESSE,
	      ETCIV_VILLE_RESIDENCE = @ETCIV_VILLE_RESIDENCE,
		  CODE_AGENCE=@CODE_AGENCE,
	      RCCM = @RCCM,
	      SEGMENT_CLIENT = @SEGMENT_CLIENT,
	      UNITE = @UNITE,
	      DEVISE = @DEVISE,
	      CA = @CA,
	      PAYS = @PAYS,
	      STATUT = @STATUT,
	      ACTIVITE_BCEAO = @ACTIVITE_BCEAO,
	      SECTEUR_D_ACTIVITE = @SECTEUR_D_ACTIVITE,
		  IDGROUPE=@GROUPE,
		  BRANCHE_ACTIVITE=@BRANCHE_ACTIVITE
	 WHERE  Ltrim(rtrim(ID_SCORING)) = Ltrim(rtrim(@ID_SCORING))

	 declare @titi varchar(30) =(select LIBELLE_GROUPE 
		 from SCOR_GROUPE
		 where Ltrim(rtrim(ID_GROUPE))=Ltrim(rtrim(@GROUPE)))
		 if @titi is not null
		 begin
	 UPDATE [dbo].[SCOR_DOSSIER]
		 set GROUPE_DOSSIER=  @titi 
		 where ID_DOSSIER=(Select top 1 ID_DOSSIER from SCOR_DOSSIER
		 where Ltrim(rtrim(ID_SCORING))=Ltrim(rtrim(@ID_SCORING)) order by DATE_DOSSIER desc)	
		 end


		-- EXEC [PS_SCOR_TRIG_INS_CONTREPARTIE]
		--@ID_SCORING =@ID_SCORING,
		--@ETCIV_MATRICULE =@ETCIV_MATRICULE,
		--@ETCIV_NOMREDUIT =@ETCIV_NOMREDUIT,
		--@CA = @CA,
		--@ACTIVITE_BCEAO =@ACTIVITE_BCEAO,
		--@SectAct = @SECTEUR_D_ACTIVITE

	end

IF @block=2
begin
	UPDATE SCOR_CONTREPARTIE SET
	      ETCIV_NOMREDUIT = @ETCIV_NOMREDUIT,
	      ETCIV_ADRESSE = @ETCIV_ADRESSE,
	      ETCIV_VILLE_RESIDENCE = @ETCIV_VILLE_RESIDENCE,
		  CODE_AGENCE=@CODE_AGENCE,
	      RCCM = @RCCM,
		  ETCIV_MATRICULE = @ETCIV_MATRICULE,
	      SEGMENT_CLIENT = @SEGMENT_CLIENT,
	      UNITE = @UNITE,
	      DEVISE = @DEVISE,
	      CA = @CA,
	      PAYS = @PAYS,
	      STATUT = @STATUT,
	      ACTIVITE_BCEAO = @ACTIVITE_BCEAO,
	      SECTEUR_D_ACTIVITE = @SECTEUR_D_ACTIVITE,
		  IDGROUPE=@GROUPE,
		  BRANCHE_ACTIVITE=@BRANCHE_ACTIVITE,
		  TYPE_PROSPECT='Reférencé'
	 WHERE  Ltrim(rtrim(ID_SCORING)) = Ltrim(rtrim(@ID_SCORING))

	set @titi =(select LIBELLE_GROUPE 
		 from SCOR_GROUPE
		 where Ltrim(rtrim(ID_GROUPE))=Ltrim(rtrim(@GROUPE)))
		 if @titi is not null
		 begin
	 UPDATE [dbo].[SCOR_DOSSIER]
		 set GROUPE_DOSSIER=  @titi 
		 where ID_DOSSIER=(Select top 1 ID_DOSSIER from SCOR_DOSSIER
		 where Ltrim(rtrim(ID_SCORING))=Ltrim(rtrim(@ID_SCORING)) order by DATE_DOSSIER desc)	
		 end


		-- EXEC [PS_SCOR_TRIG_INS_CONTREPARTIE]
		--@ID_SCORING =@ID_SCORING,
		--@ETCIV_MATRICULE =@ETCIV_MATRICULE,
		--@ETCIV_NOMREDUIT =@ETCIV_NOMREDUIT,
		--@CA = @CA,
		--@ACTIVITE_BCEAO =@ACTIVITE_BCEAO,
		--@SectAct = @SECTEUR_D_ACTIVITE

	end
end








GO

