USE [ScoringDB_MultiB]
GO

/****** Object:  StoredProcedure [dbo].[PS_VSCOR_SUPP_HISTORIQUENOTATION_T]    Script Date: 30/09/2023 11:58:52 ******/
DROP PROCEDURE [dbo].[PS_VSCOR_SUPP_HISTORIQUENOTATION_T]
GO

/****** Object:  StoredProcedure [dbo].[PS_VSCOR_SUPP_HISTORIQUENOTATION_T]    Script Date: 30/09/2023 11:58:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[PS_VSCOR_SUPP_HISTORIQUENOTATION_T]

@bloc as int,
@id_scoring as varchar(15)

as
begin
if @bloc =0
begin
Declare @IDdossier as varchar(5)
SELECT top 1 @IDdossier= D.ID_DOSSIER
From  SCOR_DOSSIER D
WHERE ID_SCORING= @id_scoring;

delete from SCOR_VALIDATION 
where ID_DOSSIER in (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
		and ID_DOSSIER <> @IDdossier

);


delete from SCOR_PROPOSITION
where ID_DOSSIER in (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
		and ID_DOSSIER <> @IDdossier
);

delete from SCOR_DOSSIER_FORMULE
where ID_DOSSIER in (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
		and ID_DOSSIER <> @IDdossier

);
delete from SCOR_NOTE_REPONSE
where ID_NOTE in (
			SELECT ID_NOTE from SCOR_NOTE_QUESTIONNAIRE
				where ID_DOSSIER in (
						SELECT  D.ID_DOSSIER
						From  SCOR_DOSSIER D
						WHERE ID_SCORING= @id_scoring
				)
);
delete from SCOR_NOTE_QUESTIONNAIRE
where ID_DOSSIER in (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
		and ID_DOSSIER <> @IDdossier

);
delete from SCOR_DOSSIER_FORMULE
where ID_DOSSIER in (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
		and ID_DOSSIER <> @IDdossier

);


declare @id_parametre_detail as varchar(4)
	select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))

  --Supression ANAFI_RATIO_DETAIL  
  DELETE FROM ANAFI_RATIO_DETAIL 
  WHERE ID_RATIO IN (SELECT ID_RATIO FROM ANAFI_RATIO 
  WHERE ID_PARAMETRE_DETAIL IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_RATIO  
  DELETE FROM ANAFI_RATIO 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))


  --Supression ANAFI_AUTRE_RATIO_DETAIL
  DELETE FROM ANAFI_AUTRE_RATIO_DETAIL 
  WHERE ID_AUTRE_RATIO IN (SELECT ID_AUTRE_RATIO FROM ANAFI_AUTRE_RATIO 
  WHERE ID_PARAMETRE_DETAIL IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_AUTRE_RATIO  
  DELETE FROM ANAFI_AUTRE_RATIO
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))


  --Supression ANAFI_TDR_DETAIL  
  DELETE FROM ANAFI_TDR_DETAIL 
  WHERE ID_TDR IN (SELECT ID_TDR FROM ANAFI_TDR
  WHERE ID_PARAMETRE_DETAIL IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_TDR  
  DELETE FROM ANAFI_TDR 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  
  
  --Supression ANAFI_TABLEAU_SYNTHETIQUE_DETAIL
  DELETE FROM ANAFI_TABLEAU_SYNTHETIQUE_DETAIL 
  WHERE ID_TABLEAU_SYNTHETIQUE IN (SELECT ID_TABLEAU_SYNTHETIQUE FROM ANAFI_TABLEAU_SYNTHETIQUE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_TABLEAU_SYNTHETIQUE
  DELETE FROM ANAFI_TABLEAU_SYNTHETIQUE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  --Supression ANAFI_BILAN_GRANDE_MASSE_DETAIL  
  DELETE FROM ANAFI_BILAN_GRANDE_MASSE_DETAIL 
  WHERE ID_BILAN_GRANDE_MASSE IN (SELECT ID_BILAN_GRANDE_MASSE FROM ANAFI_BILAN_GRANDE_MASSE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_BILAN_GRANDE_MASSE  
  DELETE FROM ANAFI_BILAN_GRANDE_MASSE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))


  --Supression ANAFI_COMPTE_RESULTAT_DETAIL
  DELETE FROM ANAFI_COMPTE_RESULTAT_DETAIL 
  WHERE ID_COMPTE_RESULTAT IN(SELECT ID_COMPTE_RESULTAT FROM ANAFI_COMPTE_RESULTAT 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_COMPTE_RESULTAT
  DELETE FROM ANAFI_COMPTE_RESULTAT 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  
  --Supression ANAFI_BILAN_DETAIL
  DELETE FROM ANAFI_BILAN_DETAIL 
  WHERE ID_BILAN IN (SELECT ID_BILAN FROM ANAFI_BILAN 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_BILAN
  DELETE FROM ANAFI_BILAN 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  --Supression ANAFI_PARAMETRE_DETAIL  
  DELETE FROM ANAFI_PARAMETRE_DETAIL
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  DELETE FROM ANAFI_PARAMETRE
  WHERE ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
		and ID_DOSSIER <> @IDdossier
)

----------------------------------------------------------------------------------------------------------------
 --Supression ANAFI_SAVE_RATIO_DETAIL  
  DELETE FROM ANAFI_SAVE_RATIO_DETAIL 
  WHERE ID_RATIO IN (SELECT ID_RATIO FROM ANAFI_SAVE_RATIO 
  WHERE ID_PARAMETRE_DETAIL IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_SAVE_RATIO  
  DELETE FROM ANAFI_SAVE_RATIO 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))


  --Supression ANAFI_SAVE_AUTRE_RATIO_DETAIL
  DELETE FROM ANAFI_SAVE_AUTRE_RATIO_DETAIL 
  WHERE ID_AUTRE_RATIO IN (SELECT ID_AUTRE_RATIO FROM ANAFI_SAVE_AUTRE_RATIO 
  WHERE ID_PARAMETRE_DETAIL IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_SAVE_AUTRE_RATIO  
  DELETE FROM ANAFI_SAVE_AUTRE_RATIO
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))


  --Supression ANAFI_SAVE_TDR_DETAIL  
  DELETE FROM ANAFI_SAVE_TDR_DETAIL 
  WHERE ID_TDR IN (SELECT ID_TDR FROM ANAFI_SAVE_TDR
  WHERE ID_PARAMETRE_DETAIL IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_SAVE_TDR  
  DELETE FROM ANAFI_SAVE_TDR 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  
  
  --Supression ANAFI_SAVE_TABLEAU_SYNTHETIQUE_DETAIL
  DELETE FROM ANAFI_SAVE_TABLEAU_SYNTHETIQUE_DETAIL 
  WHERE ID_TABLEAU_SYNTHETIQUE IN (SELECT ID_TABLEAU_SYNTHETIQUE FROM ANAFI_SAVE_TABLEAU_SYNTHETIQUE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_SAVE_TABLEAU_SYNTHETIQUE
  DELETE FROM ANAFI_SAVE_TABLEAU_SYNTHETIQUE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  --Supression ANAFI_SAVE_BILAN_GRANDE_MASSE_DETAIL  
  DELETE FROM ANAFI_SAVE_BILAN_GRANDE_MASSE_DETAIL 
  WHERE ID_BILAN_GRANDE_MASSE IN (SELECT ID_BILAN_GRANDE_MASSE FROM ANAFI_SAVE_BILAN_GRANDE_MASSE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_SAVE_BILAN_GRANDE_MASSE  
  DELETE FROM ANAFI_SAVE_BILAN_GRANDE_MASSE 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))


  --Supression ANAFI_SAVE_COMPTE_RESULTAT_DETAIL
  DELETE FROM ANAFI_SAVE_COMPTE_RESULTAT_DETAIL 
  WHERE ID_COMPTE_RESULTAT IN(SELECT ID_COMPTE_RESULTAT FROM ANAFI_SAVE_COMPTE_RESULTAT 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_SAVE_COMPTE_RESULTAT
  DELETE FROM ANAFI_SAVE_COMPTE_RESULTAT 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  
  --Supression ANAFI_SAVE_BILAN_DETAIL
  DELETE FROM ANAFI_SAVE_BILAN_DETAIL 
  WHERE ID_BILAN IN (SELECT ID_BILAN FROM ANAFI_SAVE_BILAN 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
))))

  --Supression ANAFI_SAVE_BILAN
  DELETE FROM ANAFI_SAVE_BILAN 
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  --Supression ANAFI_SAVE_PARAMETRE_DETAIL  
  DELETE FROM ANAFI_SAVE_PARAMETRE_DETAIL
  WHERE ID_PARAMETRE_DETAIL  IN(
  select ID_PARAMETRE_DETAIL from ANAFI_SAVE_PARAMETRE_DETAIL
	where  ID_PARAMETRE in (
	select ID_PARAMETRE from ANAFI_SAVE_PARAMETRE where ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
)))

  DELETE FROM ANAFI_SAVE_PARAMETRE
  WHERE ID_DOSSIER IN (
		SELECT  D.ID_DOSSIER
		From  SCOR_DOSSIER D
		WHERE ID_SCORING= @id_scoring
		and ID_DOSSIER <> @IDdossier
)
--------------------------------------------------------------------------------------------------------------


delete from SCOR_DOSSIER
where ID_DOSSIER <> @IDdossier
and ID_SCORING= @id_scoring;
UPDATE [dbo].[SCOR_DOSSIER]
   SET [NOTE_GROUPE] = ''
      ,[NOTE_PAYS] =''
      ,[NOTE_AF] = ''
      ,[NOTE_AQ] = ''
      ,[NOTE_IG] =''
      ,[NOTE_RP] =''
      ,[NOTE_SYN] =''
      ,[NOTE_PROP] =''
      ,[NOTE_VAL] =''
 WHERE ID_SCORING= @id_scoring

 UPDATE SCOR_PROPOSITION 
 SET DECISION_PROP='',
 NOTE_PROP=''
 WHERE ID_DOSSIER=@IDdossier


 end
 end





GO

