USE SCORINGDB
GO

IF OBJECT_ID('SCOR_CONTREPARTIE_INSERT') IS NOT NULL
	DROP TRIGGER SCOR_CONTREPARTIE_INSERT
GO

CREATE TRIGGER [dbo].[SCOR_CONTREPARTIE_INSERT] 
ON [dbo].[SCOR_CONTREPARTIE]
AFTER INSERT AS
BEGIN
    DECLARE @ID_SCORING [dbo].[T_CODE_12]
	DECLARE @CODE_AGENCE [dbo].[T_CODE_10] 
	DECLARE @CODE_BANQUE [dbo].[T_CODE_5] 
	DECLARE @ETCIV_MATRICULE [dbo].[T_CODE_12]
	DECLARE @ETCIV_NOMREDUIT [varchar](max) 
	DECLARE @ETCIV_ADRESSE [varchar](max) 
	DECLARE @ETCIV_VILLE_RESIDENCE [varchar](max)
	DECLARE @RCCM [varchar](max)
	DECLARE @SEGMENT_CLIENT [varchar](max) 
	DECLARE @MOIS_ARRETE [dbo].[T_DATE] 
	DECLARE @MODE_ANALYSE [dbo].[T_LIBEL_MOYEN_35] 
	DECLARE @UNITE [dbo].[T_CODE_GRAND] 
	DECLARE @DEVISE [dbo].[T_CODE_GRAND] 
	DECLARE @CA [dbo].[T_NUMERIQUE_GRAND] 
	DECLARE @PAYS [varchar](max)
	DECLARE @STATUT [dbo].[T_LIBEL_LONG_120]
	DECLARE @ACTIVITE_BCEAO [varchar](max)
	DECLARE @SECTEUR_D_ACTIVITE [varchar](max)
	DECLARE @TYPE_ANAFI [varchar](max)
	DECLARE @TYPE_PROSPECT [varchar](max)
	DECLARE @BRANCHE_ACTIVITE [varchar](max)
	DECLARE @IDGROUPE [dbo].[T_CODE_12] 


			select 
				@ID_SCORING=isnull(ID_SCORING,'')
				,@CODE_AGENCE=isnull(CODE_AGENCE,'')
				,@ETCIV_MATRICULE=isnull(ETCIV_MATRICULE,'')
				,@ETCIV_NOMREDUIT=isnull(ETCIV_NOMREDUIT,'')
				,@ETCIV_ADRESSE=isnull(ETCIV_ADRESSE,'')
				,@ETCIV_VILLE_RESIDENCE=isnull(ETCIV_VILLE_RESIDENCE,'')
				,@RCCM=isnull(RCCM,'')
				,@SEGMENT_CLIENT=isnull(SEGMENT_CLIENT,'')
				,@MOIS_ARRETE=MOIS_ARRETE
				,@MODE_ANALYSE=isnull(MODE_ANALYSE,'')
				,@UNITE=isnull(UNITE,'')
				,@DEVISE=isnull(DEVISE,'')
				,@CA=CA
				,@PAYS=isnull(PAYS,'')
				,@STATUT=isnull(STATUT,'')
				,@ACTIVITE_BCEAO=isnull(ACTIVITE_BCEAO,'')
				,@SECTEUR_D_ACTIVITE=isnull(SECTEUR_D_ACTIVITE,'')
				,@TYPE_ANAFI=isnull(TYPE_ANAFI,'')
				,@TYPE_PROSPECT=isnull(TYPE_PROSPECT,'')
				,@BRANCHE_ACTIVITE=isnull(BRANCHE_ACTIVITE,'')
			from inserted

			--SELECT @CODE_BANQUE=isnull(CODE_BANQUE,'') FROM SCOR_AGENCE WHERE rtrim(ltrim(CODE_AGENCE))=@CODE_AGENCE
			SELECT TOP 1 @CODE_BANQUE=CODE_BANQUE FROM SCOR_DONNEES_SIGNALETIQUES_ENTREPRISE

	 BEGIN TRY	

		insert INTO [WEB_BILAN_DB].[dbo].[SCOR_CONTREPARTIE]([ID_SCORING],
	  [CODE_AGENCE],[ETCIV_MATRICULE],[ETCIV_NOMREDUIT]
      ,[ETCIV_ADRESSE],[ETCIV_VILLE_RESIDENCE],[RCCM],[SEGMENT_CLIENT]
      ,[MOIS_ARRETE],[MODE_ANALYSE],[UNITE],[DEVISE],[CA],[PAYS]
      ,[STATUT],[ACTIVITE_BCEAO],[SECTEUR_D_ACTIVITE],[TYPE_ANAFI],
	  [TYPE_PROSPECT],[BRANCHE_ACTIVITE],[CODE_BANQUE])
	  VALUES(  
      @ID_SCORING
      ,@CODE_AGENCE
      ,@ETCIV_MATRICULE
      ,@ETCIV_NOMREDUIT
      ,@ETCIV_ADRESSE
      ,@ETCIV_VILLE_RESIDENCE
      ,@RCCM
      ,@SEGMENT_CLIENT
      ,@MOIS_ARRETE
      ,@MODE_ANALYSE
      ,@UNITE
      ,@DEVISE
      ,@CA
      ,@PAYS
      ,@STATUT
      ,@ACTIVITE_BCEAO
      ,@SECTEUR_D_ACTIVITE
      ,@TYPE_ANAFI
      ,@TYPE_PROSPECT
      ,@BRANCHE_ACTIVITE
      ,@CODE_BANQUE
	  )

	END TRY
	BEGIN CATCH
		 select ''
	END CATCH

END