USE [ScoringDB]
GO

/****** Object:  Trigger [SCOR_UTILISATEUR_DELETE]    Script Date: 03/03/2023 04:02:06 ******/
DROP TRIGGER [dbo].[SCOR_UTILISATEUR_DELETE]
GO

/****** Object:  Trigger [dbo].[SCOR_UTILISATEUR_DELETE]    Script Date: 03/03/2023 04:02:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE TRIGGER [dbo].[SCOR_UTILISATEUR_DELETE] 
ON [dbo].[SCOR_UTILISATEUR]
AFTER DELETE AS
BEGIN

	DECLARE @ID_USER [dbo].[T_CODE_6] 
	DECLARE @ID_PROFIL [dbo].[T_CODE_8]
	DECLARE @CODE_AGENCE [dbo].[T_CODE_10]
	DECLARE @NOM_USER [dbo].[T_LIBEL_MOYEN_35] 
	DECLARE @PRENOM_USER [dbo].[T_LIBEL_GRAND_60]
	DECLARE @EMAIL_USER [dbo].[T_LIBEL_GRAND_60] 
	DECLARE @LOGIN_USER [dbo].[T_LIBEL_MOYEN_35]
	DECLARE @PASSWORD_USER [dbo].[T_LIBEL_MOYEN_35] 
	DECLARE @DATE_USER [dbo].[T_DATE] 
	DECLARE @STATUT_USER [dbo].[T_BOOLEEN] 
	DECLARE @PARENT_SUPP [varchar](max) 
	DECLARE @PCHNG [varchar](50)

		select @ID_USER= isnull(ID_USER,''),@ID_PROFIL=isnull(ID_PROFIL,'')
		,@CODE_AGENCE = isnull(CODE_AGENCE,''), @NOM_USER= isnull(NOM_USER,'')
		,@PRENOM_USER=isnull(PRENOM_USER,''),@EMAIL_USER = isnull(EMAIL_USER,'')  
		,@LOGIN_USER=isnull(LOGIN_USER,''),@PASSWORD_USER = isnull(PASSWORD_USER,'')  
		,@DATE_USER=DATE_USER,@STATUT_USER = STATUT_USER  
		,@PARENT_SUPP=isnull(PARENT_SUPP,''),@PCHNG = isnull(PCHNG,'')  
		from inserted
				
      
    BEGIN TRY
		DELETE FROM  WEB_BILAN_DB.[dbo].[SCOR_UTILISATEUR] 
        WHERE RTRIM(LTRIM([ID_USER]))=RTRIM(LTRIM(@ID_USER))
	END TRY
	BEGIN CATCH
		 
	END CATCH
 

END

GO

ALTER TABLE [dbo].[SCOR_UTILISATEUR] ENABLE TRIGGER [SCOR_UTILISATEUR_DELETE]
GO

